### PR TITLE
[wip] add linting

### PR DESCRIPTION
**Pull request by cswl**
added some linting, found some bugs.. 

i can seperate the module changes and lint changes if you want..  

`arr` was missing in leaderboard.js .. check commit messages..

i haven't tested.. and i will be off for now..

### CODE REVIEW

**Comment by RowanHarley** [comment]
Are you sure that'll work? I've seen a lot of changes but I don't see any changes to index.js (The main one)

**Comment by cswl** [comment]
@RowanHarley  Oops, yeah forgot to add `config` and `index.js` should be fixed now...

I've broken down the commits for easy reviewing.. 

Note that I'm not familiar with the codebase...  I'm just trying to help by adding linting so you can spot  bugs easily like this one..  https://github.com/cswl/Slither-Server/commit/488498e5ca058e989c4eed527ac5ffd949be762c

There are some questions in the commit messages.. check them..  and you can reply to them as comment on commits..

**Comment by RowanHarley** [comment]
Ok thanks. I prefer the 4 space tab instead of 2 space. I can change that myself though

**Comment by cswl** [comment]
You can override the identation rules,  in your .eslintrc http://eslint.org/docs/rules/indent
There is no `n` space tab..  Do you mean soft tabs which are mostly four spaces? 

I can rebase the auto fix commit with that.. then...  
Personally I don't care about indentation as long as it's consistent.. it differs in project to project anyways.. 
Anyways.. have you checked the other commit messages..?

**Comment by RowanHarley** [comment]
Yes. I mean soft tabs which are mostly 4 spaces. Sorry for confusion. I've read the commit messages. I'll look into fixing them. About that Food.js file. It isn't used anywhere. I forgot to delete it. Other than that, it looks fine. If you could just change the soft tabs from 2 to 4 that'd be great!

**Comment by cswl** [comment]
Alright.. it's 4 spaces now..
And I deleted that Foo.js file because it was giving merge conflict..

**Comment by RowanHarley** [comment]
ok, great!

**Comment by cswl** [comment]
Wait.. did you test this?  

Speaking of tests, you might consider adding some testing framework..   like all the js projects.. you know

**Comment by RowanHarley** [comment]
I've tested it, it works fine. Also, could you recommend a testing framework? I've never really used one before so I don't know which ones are good

**Pull request merged**
